.intel_syntax noprefix
.test_case_enter:
CLFLUSH qword ptr [r14]
LFENCE
MOV qword ptr [r14], rbx
MFENCE
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MOV qword ptr [r14], rbx
MFENCE
