///
/// File: Header for the Dispatcher class,
///       responsible for instrumenting the target application with calls to service classes
///
// Copyright (C) Microsoft Corporation
// SPDX-License-Identifier: MIT

#pragma once

#include <memory>
#include <optional>

#include <dr_api.h> // NOLINT

#include "cli.hpp"
#include "logger.hpp"
#include "speculator_abc.hpp"
#include "taint_tracker.hpp"
#include "tracer_abc.hpp"
#include "types/decoder.hpp"

typedef const byte *const_app_pc;

/// @brief Internal state of the dispatcher.
enum dispatcher_state_t : uint8_t {
    OFF,          ///< The instrumentation is off.
    INSTRUMENTED, ///< Entrypoint has been found during instrumentation.
    ON,           ///< Entrypoint has been reached during execution.
    PAUSED,       ///< The instrumentation is paused (keep instrumenting but don't trace)
};
/// @brief Types of events that can trigger a state transition.
enum dispatcher_event_t : uint8_t {
    EV_ENTRY_REACHED, ///< Generated by instrument_entry
    EV_ENTRY,         ///< Generated by the entry_callback
    EV_PAUSE,         ///< Generated by the pause_callback
    EV_RESUME,        ///< Generated by the dispatch_callback on resume pc
    EV_EXIT,          ///< Generated by the dispatch_callback on resume pc
};

/// @brief Dispatcher class responsible for adding instrumentation to instructions
///        in the target application and calling the appropriate
///        service classes (e.g., Tracer, Speculator, etc)
class Dispatcher
{
  public:
    Dispatcher(cli_args_t *cli_args);
    virtual ~Dispatcher();
    Dispatcher(const Dispatcher &) = delete;
    Dispatcher &operator=(const Dispatcher &) = delete;
    Dispatcher(Dispatcher &&) = delete;
    Dispatcher &operator=(Dispatcher &&) = delete;

    // ---------------------------------------------------------------------------------------------
    // Public Attributes

    /// @param logger: shared logger for event tracing
    std::unique_ptr<Logger> logger = nullptr;
    /// @param decoder: shared instruction decode cache used by all modules
    std::unique_ptr<Decoder> decoder = nullptr;
    /// @param tracer: implements observation clause
    std::unique_ptr<TracerABC> tracer = nullptr;
    /// @param speculator: implements execution clause
    std::unique_ptr<SpeculatorABC> speculator = nullptr;
    /// @param taint_tracker: implements taint tracking for input boosting
    ///        (aka contract-based input generation)
    std::unique_ptr<TaintTracker> taint_tracker = nullptr;

    // ---------------------------------------------------------------------------------------------
    // Public Methods

    /// @brief Decides how to instrument instruction \p instr
    /// @param drcontext The drcontext of the current thread
    /// @param bb The basic block to be instrumented
    /// @param instr The instruction to instrument
    /// @return Whether a clean_call was added before the instruction
    bool instrument(void *drcontext, instrlist_t *bb, instr_t *instr);

    /// @brief Manages transitions of the internal state machine.
    /// @param event Event to handle (tells the state machine which callback is being executed)
    /// @return The new state of the state machine if there was a transition, nullopt otherwise
    std::optional<dispatcher_state_t> handle_event(dispatcher_event_t event);

    /// @brief Passes the exception down to service modules for handling
    /// @param drcontext The drcontext of the current thread
    /// @param excpt Pointer to the exception data
    /// @return True if the exception has been handled (control-flow should be redirected)
    bool handle_exception(void *drcontext, dr_siginfo_t *siginfo);

    /// @brief Tracing is done -- finalize traces.
    void finalize();

    // Setters for special PCs
    void register_entry_pc(const_app_pc pc) { entry_pc = pc; }
    void register_exit_pc(const_app_pc pc) { exit_pc = pc; }
    void register_pause_pc(const_app_pc pc) { pause_pcs.insert(pc); }
    void register_resume_pc(const_app_pc pc) { resume_pc = pc; }

    // Checks for PCs
    bool is_entry_pc(const_app_pc pc) const
    {
        return entry_pc.has_value() and entry_pc.value() == pc;
    }
    bool is_exit_pc(const_app_pc pc) const { return exit_pc.has_value() and exit_pc.value() == pc; }
    bool is_pause_pc(const_app_pc pc) const { return pause_pcs.find(pc) != pause_pcs.end(); }
    bool is_resume_pc(const_app_pc pc) const { return resume_pc.has_value() and resume_pc == pc; }

    [[nodiscard]] bool is_instrumentation_on() const { return state == dispatcher_state_t::ON; }

    // ---------------------------------------------------------------------------------------------
    // Private Attributes
  private:
    dispatcher_state_t state = dispatcher_state_t::OFF;

    std::optional<const_app_pc> exit_pc = std::nullopt;
    std::optional<const_app_pc> resume_pc = std::nullopt;
    std::optional<const_app_pc> entry_pc = std::nullopt;
    std::set<const_app_pc> pause_pcs;

    // ---------------------------------------------------------------------------------------------
    // Private Methods

    // Helpers to manage service modules
    void turn_on_instrumentation() const;
    void turn_off_instrumentation() const;

    // State machine transition functions
    void start_instrumentation();
    void start_tracing();
    void pause();
    void resume();
    void stop();

    // Instrumentation functions
    bool instrument_instruction(void *drcontext, instrlist_t *bb, instr_t *instr) const;
    void instrument_entry(void *drcontext, instrlist_t *bb, instr_t *instr) const;
    void instrument_pause(void *drcontext, instrlist_t *bb, instr_t *instr) const;
};
